nome = input('Qual seu nome? ')
print('Me informe sobre a sua data de nascimento')
dia = input('Em que dia você nasceu? ')
mes = input('Em que mês você nasceu? ')
ano = input('Em qual ano você nasceu? ')
print('Informações:')
print('Nome: ' + nome)
print('Dia: ' + dia)
print('Mês: ' + mes)
print('Ano: ' + ano)
